### ISSUE TITLE
Watch jobs don't stop correctly

### ISSUE THREAD

**Issue by iand** [filecoin-project/lily#658] opened 2021-08-18 11:25 UTC
### Describe the bug:

Stopping a watch job causes the job to hang and seems to prevent new watch jobs from starting

**Comment by frrist** [comment] 2022-04-20 19:31
caused by https://github.com/filecoin-project/lotus/pull/8441, once this lands in a release and https://github.com/filecoin-project/lily/blob/dbbc764e5f16ac943506b4d67bb48d6888c79b76/chain/watcher.go#L89 is addressed we can close this

**Closed** 2022-05-09 23:05 UTC
Labels: kind/bug, P1
