### ISSUE TITLE
Add message database error as ERROR #22P05 unsupported Unicode escape sequence

### ISSUE THREAD

**Issue by LINJINTIANDE** [filecoin-project/lily#803] opened 2021-12-17 02:59 UTC
### Describe the bug:
Add message database error as ERROR #22P05 unsupported Unicode escape sequence
![image](https://user-images.githubusercontent.com/42436479/146481819-76310901-3f94-49ee-a2c6-b00378b2fa30.png)

**Comment by iand** [comment] 2022-02-15 12:01
I think this is caused by https://github.com/filecoin-project/lily/issues/803 and should be fixed now

**Comment by frrist** [comment] 2022-04-20 19:09
via https://github.com/filecoin-project/lily/pull/844

**Closed by frrist** 2022-04-20 19:09 UTC
Labels: kind/bug
