### ISSUE TITLE
Lily gap fill error: violates unique constraint "visor_gap_reports_pkey"

### ISSUE THREAD

**Issue by placer14** [filecoin-project/lily#925] opened 2022-04-04 18:06 UTC
Lily can arrive in a state where existing records in gap reports cause updates of a fill to fail. The error reported from Lily is

`{"level":"error","ts":"2022-03-31T04:43:31.594Z","logger":"lily/schedule","caller":"schedule/scheduler.go:460","msg":"job exited with failure","id":6,"name":"lily-production-mainnet-analysis-gapfill/gapfill-/t=Sma,f=1676702,t=1679822","error":"ERROR #23505 duplicate key value violates unique constraint \"visor_gap_reports_pkey\""}`

([logz source](https://app.logz.io/kibana-7-6/app/kibana#/doc/logzioCustomerIndex*/logzioCustomerIndex220331_v29.account-104138/doc/?_g=()&id=dNtJ3n8B3NvcxIH3P01b))

The failing query:

`STATEMENT:  UPDATE "visor_gap_reports" AS "gap_report" SET status = 'FILLED' WHERE (height = 1678365) AND (task = ANY ('{"actorstatesmarket"}'))\n`.

I'm not sure what causes the DB to arrive in this state, but I know this range of epochs have had multiple fill/find operations. I'm not sure how we should correct this problem, but I prefer that truncation of the gap reports table is not expected solution.

## ~Where to start~ Ideas

- Perhaps you could remove the GAP report and update the existing FILLED record with the new timestamp instead. I hate that this mutates data on this table. (this seems the easiest quick fix)
- FILL could remove existing records for the tasks it's FINDing from gap reports table before starting. (middle ground that I could agree with which I would probably insert warnings or strong documentation to be careful of this sharp edge when executing gap fill)
- We could fix the constraint to remove uniqueness on status and change UPDATE to select the correct gap report for updating instead of expecting there to be only one. (hardest, preferred)

**Comment by frrist** [comment] 2022-04-28 01:14
This has been addressed by #884

It was caused by calling https://github.com/filecoin-project/lily/blob/v0.8.8/chain/find.go#L82 after the query that found gaps https://github.com/filecoin-project/lily/blob/v0.8.8/chain/find.go#L67

**Closed by frrist** 2022-04-28 01:14 UTC
Labels: kind/bug
