### ISSUE TITLE
Error parsing some messages 

### ISSUE THREAD

**Issue by davidgasquez** [filecoin-project/lily#1092] opened 2022-11-17 09:08 UTC
The task `parsed_message` is returning some errors when running `lily job walk` on some archival snapshots. 

### Steps to Reproduce:

1. Obtain an Archival Snapshot: `aws s3 cp "s3://sentinel-backfill/historical-exports/snapshot_14400_17282_1666948059.car.zst" .`
2. Extract it: `unzstd snapshot_14400_17282_1666948059.car.zst -o /tmp/snapshot.car`
3. Initialize Lily: `lily init --config=config.toml --import-snapshot /tmp/snapshot.car`
4. Start Lily Daemon: `nohup lily daemon --config=config.toml --bootstrap=false &> lily.log &`
5. Run a walk that covers from `14800` to `15000`] : `lily job run --storage=CSV walk --from 14800 --to 15000`
6. Check Visor Processing Reports: `cat visor_processing_reports.csv | grep ERROR`

This is the `config.toml` file:
```toml
[Storage]
    [Storage.File]
        [Storage.File.CSV]
            Format = "CSV"
            Path = "/tmp/data"
            OmitHeader = false
            FilePattern = "{table}.csv"
```

The `visor_processing_reports.csv` has the following error:
```
14880,bafy2bzaceam6cgi52qzrp26yeubt5hlsupwt66gqixbh7ndhbwofnz7ct6e3g,walk_1668613865,parsed_message,2022-11-16T16:37:05.909Z,2022-11-16T16:37:05.94Z,ERROR,,"[{""Cid"":{""/"":""bafy2bzaceauxnnqgcpzezkwhaclnjmxzvecnmb7fgvggeiiqepliqsryvyuwe""},""Error"":""failed to parse message params: parse message params cbor decode into SubmitWindowedPoSt fil/1/storageminer:(bafkqaetgnfwc6mjpon2g64tbm5sw22lomvza.5) return (hex): f6 failed: cbor input should be of type array""}]"
14820,bafy2bzaceclxagmd45yiljtuawxmuqu7s4r3au7nmi4meoksrluenj5bfn2yc,walk_1668613865,parsed_message,2022-11-16T16:38:07.819Z,2022-11-16T16:38:07.851Z,ERROR,,"[{""Cid"":{""/"":""bafy2bzacedla6kezztgkc5vm6nezna6473v7uy2lkvltqvmkfpqmidy3ya4ne""},""Error"":""failed to parse message params: parse message params cbor decode into SubmitWindowedPoSt fil/1/storageminer:(bafkqaetgnfwc6mjpon2g64tbm5sw22lomvza.5) return (hex): f6 failed: cbor input should be of type array""}]"
```

And the `lily.log` file has these lines:
```json
{"level":"debug","ts":"2022-11-17T09:02:30.629Z","logger":"lily/integrated/tipset","caller":"tipset/tipset.go:182","msg":"task report","height":"14880","task":"parsed_message","reporter":"walk_1668675699","status":"ERROR","duration":0.079606731}
{"level":"warn","ts":"2022-11-17T09:02:30.629Z","logger":"lily/index/manager","caller":"integrated/manager.go:122","msg":"task failed","height":"14880","reporter":"walk_1668675699","task":"parsed_message","status":"ERROR","errors":[{"Cid":{"/":"bafy2bzaceauxnnqgcpzezkwhaclnjmxzvecnmb7fgvggeiiqepliqsryvyuwe"},"Error":"failed to parse message params: parse message params cbor decode into SubmitWindowedPoSt fil/1/storageminer:(bafkqaetgnfwc6mjpon2g64tbm5sw22lomvza.5) return (hex): f6 failed: cbor input should be of type array"}],"info":""}
{"level":"debug","ts":"2022-11-17T09:04:36.012Z","logger":"lily/integrated/tipset","caller":"tipset/tipset.go:182","msg":"task report","height":"14820","task":"parsed_message","reporter":"walk_1668675699","status":"ERROR","duration":0.049460683}
{"level":"warn","ts":"2022-11-17T09:04:36.012Z","logger":"lily/index/manager","caller":"integrated/manager.go:122","msg":"task failed","height":"14820","reporter":"walk_1668675699","task":"parsed_message","status":"ERROR","errors":[{"Cid":{"/":"bafy2bzacedla6kezztgkc5vm6nezna6473v7uy2lkvltqvmkfpqmidy3ya4ne"},"Error":"failed to parse message params: parse message params cbor decode into SubmitWindowedPoSt fil/1/storageminer:(bafkqaetgnfwc6mjpon2g64tbm5sw22lomvza.5) return (hex): f6 failed: cbor input should be of type array"}],"info":""}
{"level":"debug","ts":"2022-11-17T09:06:35.780Z","logger":"lily/integrated/tipset","caller":"tipset/tipset.go:182","msg":"task report","height":"14761","task":"parsed_message","reporter":"walk_1668675699","status":"ERROR","duration":0.071588629}
{"level":"warn","ts":"2022-11-17T09:06:35.780Z","logger":"lily/index/manager","caller":"integrated/manager.go:122","msg":"task failed","height":"14761","reporter":"walk_1668675699","task":"parsed_message","status":"ERROR","errors":[{"Cid":{"/":"bafy2bzaceduqufv3myqbpnptakcecn2ygmgboup5gpljentjdcmflckvi6uni"},"Error":"failed to parse message params: parse message params cbor decode into SubmitWindowedPoSt fil/1/storageminer:(bafkqaetgnfwc6mjpon2g64tbm5sw22lomvza.5) return (hex): f6 failed: cbor input should be of type array"}],"info":""}
```

Something similar is happening around epoch ~36000, but with a sightly different error message:
```

37027,bafy2bzaced6n4s2dt4csli7euulioj4pmhzrz7knrpnh4ae4lefdqe7l6wwi6,walk_1668624722,parsed_message,2022-11-16T19:01:25.36Z,2022-11-16T19:01:25.431Z,ERROR,,"[{""Cid"":{""/"":""bafy2bzacea7myhsufej2eeptrlwiwk5ajyjukozwispmakghkhbsh4fhgzwds""},""Error"":""failed to parse message params: parse message params cbor decode into Approve fil/1/multisig:(bafkqadtgnfwc6mjpnv2wy5djonuwo.3) return (hex): 82019820184318dd18b70f18a71849188618631825188718e118e1189918bc18d30318d7187e18aa181e1833186c18f8188b18bc18a018d3187118aa185818f9188a failed: expected byte array""}]"
37010,bafy2bzaceaig345jb7rqhapipzonipmv4bw3qdfr4gfklydg67kb6yv7com4y,walk_1668624722,parsed_message,2022-11-16T19:01:49.365Z,2022-11-16T19:01:49.429Z,ERROR,,"[{""Cid"":{""/"":""bafy2bzaceatkuv4zhi6vdxrumhmbksu73q7kgboxl3cizyelfdfod3ueoocfe""},""Error"":""failed to parse message params: parse message params cbor decode into Approve fil/1/multisig:(bafkqadtgnfwc6mjpnv2wy5djonuwo.3) return (hex): 8201982018dd18a718a4186b187f18da18ed183318d31823185b185e184b183818e2183b182017184c189d189f18cc182d1861189a183701187b184d18d8183818ab failed: expected byte array""}]"
36944,bafy2bzaceccnakbs7oifv5hlf3hijm3zsizotdeedn2qhqtou27u3rryii5dc,walk_1668624722,parsed_message,2022-11-16T19:03:20.589Z,2022-11-16T19:03:20.621Z,ERROR,,"[{""Cid"":{""/"":""bafy2bzacedrk4zwzolg2dnsmxx2p4bjoo7f2vzxp7bjqisikjefx64kje33cw""},""Error"":""failed to parse message params: parse message params cbor decode into Approve fil/1/multisig:(bafkqadtgnfwc6mjpnv2wy5djonuwo.3) return (hex): 8201982018b618e71847185718ff18e9189b187a0a18fb182218a718f3183018820a184e186d18fa18680418d818fc18d718dd1891184c18340b1885187c18f3 failed: expected byte array""}]"
36922,bafy2bzacea6bzd2jv5dojgl2xi2iyd23pivnvuu7u5vb62yihginz5zc2m6dq,walk_1668624722,parsed_message,2022-11-16T19:03:51.566Z,2022-11-16T19:03:51.621Z,ERROR,,"[{""Cid"":{""/"":""bafy2bzacecotqmtd3p5qrzv5hewfufi6t7ukspbjkhagv2wxp2kzgwo6ncutk""},""Error"":""failed to parse message params: parse message params cbor decode into Approve fil/1/multisig:(bafkqadtgnfwc6mjpnv2wy5djonuwo.3) return (hex): 8200982018b618e71847185718ff18e9189b187a0a18fb182218a718f3183018820a184e186d18fa18680418d818fc18d718dd1891184c18340b1885187c18f3 failed: expected byte array""}]"
36912,bafy2bzacedagpro2f3zffzbxttoor5szqjvwlg6adstlmv3vhc5mhv5cp2zzy,walk_1668624722,parsed_message,2022-11-16T19:04:03.114Z,2022-11-16T19:04:03.172Z,ERROR,,"[{""Cid"":{""/"":""bafy2bzaceb6v5rnmhkdnxx4xrhx3zq2kutbxmauedxopcxylqbfz5fq2hkiby""},""Error"":""failed to parse message params: parse message params cbor decode into Approve fil/1/multisig:(bafkqadtgnfwc6mjpnv2wy5djonuwo.3) return (hex): 8200982018b618e71847185718ff18e9189b187a0a18fb182218a718f3183018820a184e186d18fa18680418d818fc18d718dd1891184c18340b1885187c18f3 failed: expected byte array""}]"
36888,bafy2bzacea52bmomee2iufzxy36wzuld6w2zxtay3ohuqyk23bgyo7klmbq2s,walk_1668624722,parsed_message,2022-11-16T19:04:35.99Z,2022-11-16T19:04:36.053Z,ERROR,,"[{""Cid"":{""/"":""bafy2bzacebqr3defpqhljzktvlv6lqilbkv5qggh6grww3b4bjiib7cbpzxia""},""Error"":""failed to parse message params: parse message params cbor decode into Approve fil/1/multisig:(bafkqadtgnfwc6mjpnv2wy5djonuwo.3) return (hex): 8200982018b618e71847185718ff18e9189b187a0a18fb182218a718f3183018820a184e186d18fa18680418d818fc18d718dd1891184c18340b1885187c18f3 failed: expected byte array""}]"
36880,bafy2bzaceb5ekenilxsaotlptx7vxrzxvowasqzvkjuy57kqbk3won4wn7dos,walk_1668624722,parsed_message,2022-11-16T19:04:48.749Z,2022-11-16T19:04:48.789Z,ERROR,,"[{""Cid"":{""/"":""bafy2bzaceabrez25khsfltuiireeng2p3avoniczz2scfsi54hykltoxjeslk""},""Error"":""failed to parse message params: parse message params cbor decode into Approve fil/1/multisig:(bafkqadtgnfwc6mjpnv2wy5djonuwo.3) return (hex): 8200982018b618e71847185718ff18e9189b187a0a18fb182218a718f3183018820a184e186d18fa18680418d818fc18d718dd1891184c18340b1885187c18f3 failed: expected byte array""}]"
```

Also on epoch `64722` and around the `98300`s:
```
64722,bafy2bzacecmmhb3iaqbqtrswnkcadan24swxwowfvd7e3j3tx4454cenhuxke,walk_1668683296,parsed_message,2022-11-17T11:56:13.89Z,2022-11-17T11:56:13.932Z,ERROR,,"[{""Cid"":{""/"":""bafy2bzacebf3xppdgr5txljoz2teinyxbym2y7qm35diwhpudpvwrogywys2m""},""Error"":""failed to parse message params: missing actor code""},{""Cid"":{""/"":""bafy2bzaceajyl6ujvzowkurcc55qtmbquqagb2zt6jt3fdrvjdvxesuvucnwg""},""Error"":""failed to parse message params: parse message params cbor decode into Constructor fil/1/account:(bafkqadlgnfwc6mjpmfrwg33vnz2a.1) return (hex): 62797465206172726179 failed: cbor type for address unmarshal was not byte string""}]"
99420,bafy2bzacecgexyg3xpii3fosmihucyy3jdcoo5rwutxgnkoata3lje36g3k5c,walk_1668685232,parsed_message,2022-11-17T12:40:45.146Z,2022-11-17T12:40:45.221Z,ERROR,,"[{""Cid"":{""/"":""bafy2bzaceal3x4wzwrare7zvvl7k6gagr6uizf7rlys7cjpycwh2wlqmu7gbc""},""Error"":""failed to parse message params: parse message params cbor decode into Constructor fil/1/account:(bafkqadlgnfwc6mjpmfrwg33vnz2a.1) return (hex):  failed: EOF""}]"
99410,bafy2bzaceasr55nv56rrbmcup64yutqci3fcbl6nfey365cktuslzepfroko6,walk_1668685232,parsed_message,2022-11-17T12:41:07.974Z,2022-11-17T12:41:08.035Z,ERROR,,"[{""Cid"":{""/"":""bafy2bzacebtatz5hs5dsmaovk4te6af45xq6kzev7qssamkbxde3kuudbk6ne""},""Error"":""failed to parse message params: parse message params cbor decode into Constructor fil/1/account:(bafkqadlgnfwc6mjpmfrwg33vnz2a.1) return (hex): 63397465206172726179 failed: cbor type for address unmarshal was not byte string""}]"
99178,bafy2bzaced47pa5kmm6nkve5eaqgr6i2o22r526zsb5oueft7xwokhzy3xsno,walk_1668685232,parsed_message,2022-11-17T12:50:42.485Z,2022-11-17T12:50:42.546Z,ERROR,,"[{""Cid"":{""/"":""bafy2bzacednmwgumvkye5vmxffamnf3dfrnqfjfc7u4lyilbubr22fa4nht62""},""Error"":""failed to parse message params: parse message params cbor decode into Constructor fil/1/account:(bafkqadlgnfwc6mjpmfrwg33vnz2a.1) return (hex): 63397465206172726179 failed: cbor type for address unmarshal was not byte string""}]"
98581,bafy2bzacecg3uu6dbl5cgqgiclcrhsjtukc4aykdlftd7azynrkq77oyf5umy,walk_1668685232,parsed_message,2022-11-17T13:15:56.486Z,2022-11-17T13:15:56.553Z,ERROR,,"[{""Cid"":{""/"":""bafy2bzaceasyqjlm277wgfm627kciccvxjo4ys46ggvwwn7a5a3flgsk472xs""},""Error"":""failed to parse message params: parse message params cbor decode into Constructor fil/1/account:(bafkqadlgnfwc6mjpmfrwg33vnz2a.1) return (hex):  failed: EOF""}]"
98474,bafy2bzaceajnbvvqmrvjhvtyxfbdqtkwktx76665wn3zwxmdf6mpet6nbp5r2,walk_1668685232,parsed_message,2022-11-17T13:20:22.851Z,2022-11-17T13:20:22.915Z,ERROR,,"[{""Cid"":{""/"":""bafy2bzaceakly7jjrbmd7cs2densooqvanpm2nsb2uucc3ndywubqvrk5yqg4""},""Error"":""failed to parse message params: parse message params cbor decode into Constructor fil/1/account:(bafkqadlgnfwc6mjpmfrwg33vnz2a.1) return (hex): 63397465206172726179 failed: cbor type for address unmarshal was not byte string""}]"
98457,bafy2bzacebg3kktev3negukfq6gkbvqsrqocw6cbm42ubb54zztpkb7xj6nis,walk_1668685232,parsed_message,2022-11-17T13:21:04.704Z,2022-11-17T13:21:04.79Z,ERROR,,"[{""Cid"":{""/"":""bafy2bzaceb2m6cce33wlkkrqx6bqhdvgfl3xn2xaaizhc4rk4jl7ceaiugybc""},""Error"":""failed to parse message params: parse message params cbor decode into Constructor fil/1/account:(bafkqadlgnfwc6mjpmfrwg33vnz2a.1) return (hex): 63397465206172726179 failed: cbor type for address unmarshal was not byte string""}]"
98379,bafy2bzacecyxdeldv3cqs4mo24t75vfwf4rteyyx2uotx4jkd54khrlbl5itu,walk_1668685232,parsed_message,2022-11-17T13:24:16.59Z,2022-11-17T13:24:16.649Z,ERROR,,"[{""Cid"":{""/"":""bafy2bzacebm7kufjpsp3bbjlrdbrx3lk3e2ye4cemiehorx2nhkxo2mlu2ms2""},""Error"":""failed to parse message params: parse message params cbor decode into Constructor fil/1/account:(bafkqadlgnfwc6mjpmfrwg33vnz2a.1) return (hex):  failed: EOF""}]"
```

### Lily Version: v0.12.0+6-g8d3c4b7

**Comment by frrist** [comment] 2022-11-29 20:39
These errors were all caused by attempting to parse messages whose receipts had non-zero exit codes, e.g.
https://filfox.info/en/message/bafy2bzaceauxnnqgcpzezkwhaclnjmxzvecnmb7fgvggeiiqepliqsryvyuwe
https://filfox.info/en/message/bafy2bzacedla6kezztgkc5vm6nezna6473v7uy2lkvltqvmkfpqmidy3ya4ne
https://filfox.info/en/message/bafy2bzaceasyqjlm277wgfm627kciccvxjo4ys46ggvwwn7a5a3flgsk472xs

In v0.13.0 we now skip parsing such messages and opt only to parse messages that have applied successfully:
https://github.com/filecoin-project/lily/pull/1080/files#diff-c96f9f1d3055debee1b4fbcb5e6bf91714d001bb9d84d598dfd247d2c1c8f166R109

Closed via #1080 

@davidgasquez, you should be able to re-run the walk jobs for these heights without errors using lily@v0.13.0

**Closed by frrist** 2022-11-29 20:39 UTC
Labels: kind/bug
